import React from 'react';
import SEO from '@/components/common/SEO';
import { Link } from 'react-router-dom';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

export default function Terms() {
    return (
        <div className="min-h-screen pt-24 pb-12 md:pb-20 container-padding flex flex-col justify-center">
            <SEO 
                title="Terms of Service" 
                description="Read the Terms of Service for RSMK Technologies regarding our software products and systems demos." 
                keywords="Terms of Service, RSMK Technologies, user agreement, software terms" 
                url="/terms" 
            />

            <div className="max-w-3xl mx-auto w-full">
                <div className="flex items-center justify-between mb-8">
                    <Link 
                        to="/" 
                        className="inline-flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400 hover:text-primary transition-colors group"
                    >
                        <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
                        Back to Homepage
                    </Link>
                    
                    <div className="flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400 font-mono">
                        <ShieldCheck size={14} className="text-emerald-500" />
                        <span>Terms Verified</span>
                    </div>
                </div>

                <div className="prose dark:prose-invert max-w-none space-y-6">
                    <h1 className="text-3xl sm:text-4xl font-bold font-heading text-secondary dark:text-white mb-2">
                        Terms of Service
                    </h1>
                    <p className="text-xs text-slate-500 dark:text-slate-400">Last updated: May 24, 2026</p>
                    
                    <hr className="border-slate-200 dark:border-slate-800" />

                    <div className="space-y-4">
                        <h2 className="text-xl font-bold text-secondary dark:text-white">1. Acceptance of Terms</h2>
                        <p className="text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
                            By accessing or using our websites, software demos, and technical tools (collectively "Services"), you agree to be bound by these Terms of Service. If you do not agree to all terms, you must discontinue using our services.
                        </p>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-xl font-bold text-secondary dark:text-white">2. Permitted Use</h2>
                        <p className="text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
                            Our services and codebases are provided for project evaluation, engineering education, and system demonstrations. You agree not to abuse, disrupt, or execute malicious load testing against our active backend APIs, including the Mani AI chatbot server.
                        </p>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-xl font-bold text-secondary dark:text-white">3. Disclaimer of Warranties</h2>
                        <p className="text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
                            Our software demos, custom APK releases, and simulated models are provided "as-is" without warranty of any kind. RSMK Technologies does not assume liability for errors in custom firmware, power systems simulation outputs, or calculations generated by tools like ColorOhm.
                        </p>
                    </div>

                    <div className="space-y-4">
                        <h2 className="text-xl font-bold text-secondary dark:text-white">4. Modifications to Services</h2>
                        <p className="text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
                            We reserve the right to modify, suspend, or deprecate any software tools, API endpoints, or portfolios at any time without notice. For inquiries, contact us at <a href="mailto:rsmk.technologies@rsmk.co.in" className="text-primary hover:underline">rsmk.technologies@rsmk.co.in</a>.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
